### ISSUE TITLE
 not RFC 2822 compliant

### ISSUE THREAD

**Issue by whowatches** [zeknox/scripts#4]
Hi there, 

When pentesting this against a company who uses GAPPS (gmail), the email bounces with the following error:

{{{
Our system has detected that this message is\n550-5.7.1 not RFC 2822 compliant. To reduce the amount of spam sent to Gmail,\n550-5.7.1 this message has been blocked. Please review\n550 5.7.1 RFC 2822 specifications for more information. x7si17045593eeo.307 - gsmtp
}}}

**Comment by zeknox** [comment]
sendmail currently does not support SSL/TLS connections, I am working on a new ruby on rails application to address this issue. Thanks

**Comment by whowatches** [comment]
this isnt ssl/tls related i don't think. usually rfc2822 refers to the headers. Like invalid 'From:' ,multiple 'To:' headers or something similar. I'll resend it elsewhere see what I can find out and post back here. 

thanks again

**Comment by whowatches** [comment]
bah, my fault, **note to self, check your own message.txt for correct formatting before asking elsewhere...**\*  Closing as invalid
